server:
  port: 30030
  shutdown: graceful
spring:
  application:
    name: ZZS-IAM
  cloud:
    gateway:
      metrics:
        enabled: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 30S
        pool:
          max-idle-time: 30S
          max-life-time: 10M
          eviction-interval: 10S
          metrics: true
  codec:
    max-in-memory-size: 10MB
  jackson:
    locale: zh_CN
    time-zone: 'GMT+8'
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
  profiles:
    active: local
management:
  endpoints:
    web:
      exposure:
        include: 'prometheus'
  metrics:
    export:
      jmx:
        enabled: false

endpoints:
  jmx:
    enabled: false
